# Builds Gatsby file public folder
FROM node:16-buster AS builder

WORKDIR /app

COPY . .

RUN yarn install && yarn build

# Nginx to run website
FROM arm64v8/nginx:alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /app/public .

ENTRYPOINT ["nginx", "-g", "daemon off;"]